repositoryUrl: https://github.com/dynamsoft-docs/label-recognition-docs/blob/master
repository: Dynamsoft/label-recognition-docs
docFullPath: https://www.dynamsoft.com/label-recognition/docs
firstLevelUrl: /label-recognition/docs/web
docRootName: "Label Recognizer JS Edition" 
docHomePage: /label-recognition/docs/web/programming/javascript/

parameters-reference: /label-recognition/docs/core/parameters/reference/

js: /label-recognition/docs/web/programming/javascript/
js-api: /label-recognition/docs/web/programming/javascript/api-reference/
js-release-notes: /label-recognition/docs/web/programming/javascript/release-notes/

assets: /label-recognition/docs/core/assets/
edit_icon: /label-recognition/docs/core/assets/img-icon/edit-icon.png
smile_icon: /label-recognition/docs/core/assets/img-icon/icon-smile.png
sad_icon: /label-recognition/docs/core/assets/img-icon/icon-sad.png
dbr_icon: /label-recognition/docs/core/assets/img-icon/icon-dbr.svg
dwt_icon: /label-recognition/docs/core/assets/img-icon/icon-dwt.svg
dnt_icon: /label-recognition/docs/core/assets/img-icon/icon-dnt.svg

release-notes: /label-recognition/docs/core/release-notes/
license-activation: /label-recognition/docs/core/license-activation/

useVersionTree: true

baseurl: "/label-recognition/docs/web"
plugins:
  - jemoji


edition: js

defaults:
  - scope:
      path: ""
    values:
      category: "original-repo"
      edition: "algorithm"
  - scope:
      path: "programming/javascript"
    values:
      category: "js-repo"
      edition: "js"
  - scope:
      path: "mobile/programming/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "mobile/programming/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "server/programming/c"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/cplusplus"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/dotnet"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/python"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/java"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true

url: "https://www.dynamsoft.com" # sitemap root

